#服务端口
server:
  port: 6087
# 应用名称
spring:
  profiles:
    active: local
  application:
    name: ${prefix.distinction.name:Dismai}-pay-service
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      generator:
        WRITE_NUMBERS_AS_STRINGS: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-pay-${spring.profiles.active}.yaml
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 3000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: status
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
feign:
  sentinel:
    enabled: false
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 512
    response:
      enabled: true
management:
  metrics:
    tags:
      application: pay-service
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    elasticsearch:
      enabled: false
  prometheus:
    metrics:
      export:
        enabled: true
jasypt:
  encryptor:
    password: bgtjkjl!%^sdc
    algorithm: PBEWithMD5AndDES
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.dismai.controller
#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: false
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
alipay:
  appId: 9021000164636210
  sellerId: 2088721101931205
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCQBKmx2DbQQaTGSTkQ7GnPYJL1qcK4AVue/pDWvHdPp+qvN2FbgaXGPpBttI/Ez+bZoW9eRlASEmZtkHBZprRQGOxGiYL/aC4IU/TEynPpOO/V1502He/ztcSQD6QBKYrrRJlzBX/ivCj+iC03Hw2G/tOf0zSHXih0M1RuLrgnRPrSyRcUrVxVkC7pfJFepXxWJBl4gWbfjSVVkf2YdX7S1uvAesnt/6S+NC2v72zo7Ii8XSIsaGy3Dnpmg61iiaJe2b5B3u/Tvq6g63H8d23om3hZR+Ld7tS+tn+52QuCZEC2GVhF4n32Snl/Y53I9qpWYWqlLObdybhOiyllS7zdAgMBAAECggEAOdqVrMrVoi1smvcZRJIkI1mBT8ylWzO4cZOD7a+CIm6rGT4fDxpy1MOXU2rAgmieLPjr+yw1yDy6BvOKHomYT8DjUaa2CBH6w/+uCUvm6l6kAfx+vBmkpftz/gc6c/kTRFWnawxfhl7d/PoJZ+ZCkeNWchLvPB34FE32cdi0w5kU8+O3d3VNm4GHTB60Lm9Ai5BbdsNGmJnADQjKQE992h07CD53hMjq+nGuvPlw+Ky0Wld8+qNaiFpgpx65uwaqbDp9U9dfWXDnehRZYmWhgR0D8YDuHK2nNw7I61mK2MOY0EjAQiPd3/SLICqgtdX3PEgrcMACGL0aoOYOPQqhJQKBgQDxVcw7Eup3Q6OI2RZy759/FXeRlfiRJL9flOFxXCIz/iMBtkR8Ae0z+Vgjch8usnsXVDluxJnSOHqLPpGxfM7KLMPfAMkqxLDnHFNorOEW55vsDl/WGpzzk0dRnhDcgYYoub0AqiWVJEd8TiivpZjAfiCYNjHBuy7C28sXGHjDTwKBgQCYxQF+hR+GDOLZVOdJpSlf5KryDvwbk87JghlFXgBnkZaCAmsgbnb30fN9/2JxFjYx/MKsS88PESCDD5BZIdREniDJXNSC11Vqc3jMgBb3z1Bhw99ZyhmC60u1K+3GLV6MyjgRI/9D0WUfFTBhi83iCzZGOdrw7iSlIRAvXR9iEwKBgQDs0gvawGIy7L3ykU0VNo2mULOHusoz7AKb0eY0rnul17IUgP7NTbquMPXLurZcxapCp1TAnM5xWxjtwVWI/PeTr7/5+rRtcpxB/irfYh5zso3wY96ppG32G8V1kw3qxHOZTULp/w1oQDSiB7SnQHIYGuzzUOMcwAlQEA1IOaxvwwKBgEaz7qQagmNs9VQ2OjDYUpTB5OfQTZeJycty/bUf8zn7pFeZPPEujrrVHUbz+iBycjSiUYqiLzs+5vghLOJDiNUVBgGLiALiG/L/bCnhIkAgX4hPub/5i+MOeORpZ0sv1jF8qYQtT8eYUp+XE+QhavCx1bWcsxqMbMNL0QzKoWqnAoGAapbjGmgpjmR6aWgpo5uVp8jNqo+7smS8LLNwSn/1Lzi0DRCxLstKOvlEtX1F1JiFM7+z6znLIrg4EKf5jZTfadCmaR8t/wE+1HjW2fJ6pOQcExt3HIodZ1UQx9FxgZOvHQclHord/xGUArvzF0A0uikpeoQH/9NTLq+cm9zHQdY=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk5RXI/gTu7wHhwuyuz2XnKWnETtUAF7RqIxqFgS9K+97kiPrO7P2AUwyfW6QxwlhHj5rbt2HaFIc57imP2VgHnCMxH68ERROSKkAY7eYojlOaqKVEGvOmvBFzM1SDzd/TdJwR1Ch88t3HSG/9I2fUN/HGjNI1MiNLGYkaAbuUJzZkTs7tW9+zrJmbjJyd/dD4+cXbtaTWBoNKo14reGhh6YvxKzl2teajgNPOkBUhVr733cLr6GXlaksVdDZ/KF6KygeE9Fh65hXgd/C/COg3pVN1wkpJGhtcglHLSze2SXNtaqlBx431c/wOx/e+8YlBV9FYPNZQ39e3mc7o1O0bwIDAQAB
  contentKey: 43qu8K/LCThAv0EGu7CwFw==